### ISSUE TITLE
RWB Jasper report change for loksahabagh

### ISSUE THREAD

**Issue by vaijayanthisundaram** [avniproject/GDGSGOM#10]
Hiral has asked for changes in current Jasper report (district wise dashboard work order detail ) to include values from the new loksahabagh form.

- [x] In district wise dashboard work order detail report, add columns for "total silt excavated by loksahabagh" and "total water bodies registered by loksahabagh”. 
- [x] Update total silt excavated formula to include this new column.

More changes requested from Hiral :

- [x] Remove columns "Total Waterbodies Planned", "Total number of workorders completed" and "Number of work orders in progress".
- [x] Add 1 column "Workorders with Daily recordings" instead of above mentioned 3 columns.

**Comment by vaijayanthisundaram** [comment]
Dinesh, I have made these changes in a test location at : https://reporting-jasper.avniproject.org/jasperserver/flow.html?_flowId=viewReportFlow&_flowId=viewReportFlow&ParentFolderUri=%2FTestReports%2FVaiju_Test_reports&reportUnit=%2FTestReports%2FVaiju_Test_reports%2FDistrict_wise_dashboard_workorder_detail&standAlone=true

Please check.

**Comment by Dinesh2019** [comment]
<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzVEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc2f7fa1be440b88f45d8de829d6e2cc8c995487/Screenshot%202023-12-07%20at%206.24.19%E2%80%AFPM.png" alt="Screenshot 2023-12-07 at 6.24.19 PM.png" />

**Comment by vaijayanthisundaram** [comment]
@Dinesh2019 this is not an error with the report but is related to the environment used for testing , since query is for all rwb orgs and only gdgsuat is being used for testing. moving back to ready for qa.

**Comment by Dinesh2019** [comment]
@nupoorkhandelwal @sachin can anyone review this code since it is prod env i unable to test it urgent

**Comment by sachsk** [comment]
@Dinesh2019 have you tested the filters? its not working
