### ISSUE TITLE
App Feedback GDGS 2024

### ISSUE THREAD

**Issue by adamsanadi6** [avniproject/GDGSGOM#14]
- [x]  Change card name :-active workorder to "Daily recording farmer and machine"
- [x]  logic for offline dashboard has to be corrected: "Daily recording farmer and machine" (same as RWB active work order)
- [x]  In farmer endline :- Remove regex from Village name
- [x]  In farmer reg:- Category of farmer:-> change "Semi medium (5-9.55 acres)" to "Semi medium (5-9.99 acres)"
- [x]  In machine reg :-> if machine name starts with "pc" then show error on the "Type of machine" if user select JCB.

**Comment by salilsamanvay** [comment]
I have added one more points on this feedback card on 22nd Jan 2023

**Comment by adamsanadi6** [comment]
@Dinesh2019 Salil has added new point which is
- [x] logic for offline dashboard has to be corrected: "Daily recording farmer and machine" (same as RWB active work order)
