### ISSUE TITLE
RWB permissions issue

### ISSUE THREAD

**Issue by sachsk** [avniproject/GDGSGOM#15]
## Context
We have uploaded the gdgs & rwb 24 bundle from Avni infra to RWB infra due to bundle bug group permissions are not updated on the RWB infra.

- [x] Give the permissions to user groups on RWB infra as per Avni infra for gdgs24uat ans rwb24uat org
- [x] Give the permissions to user groups on RWB infra as per Avni infra for rwb24uat ans rwb24uat org

Note : in old org there are multiple groups present but in new org there will be a 2 user groups named as primary users and Project Leads

**Comment by Dinesh2019** [comment]
@sachsk still the user group are not updated in the new env
