### ISSUE TITLE
new UAT GDGS 2024 org creation

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/GDGSGOM#2]
## context: 
as the data size is too much for each catchment for every season, it has been agreed with the client that each season/year we will create a new org for each implementation, below are the 3 organizations that are to be created, so as a standard process to make suggested changes first we will create a UAT org and then move the change to live org.

requirement document link: https://docs.google.com/spreadsheets/d/17-PuEEYXFgsCqm60Eg1QCj7LfIFVTbvZWx-I26ihBlM/edit#gid=654347753

- [x] New org: GDGSGOM 2024_UAT, to create this bundle of old org: GDGSGOM is to be uploaded.
  - Schema name: gdgs24uat
  - user suffix: gdgs24uat
  - DB user: gdgs24uat

**Comment by nupoorkhandelwal** [comment]
- [x] Add the same concept 2024 with same UUID under Year from RWB 2024 UAT org

**Comment by BEULAHEVANJALIN** [comment]
GDGSGOM bundle: [GDGSGOM.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFlxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e30e807c66fd5b9fc8b601b568f73260c638473e/GDGSGOM.zip)

**Comment by BEULAHEVANJALIN** [comment]
https://gist.github.com/BEULAHEVANJALIN/06bb2f9bc338b4f2becb8d424ea908e6
