### ISSUE TITLE
[GDGS 2024] UAT - Farmer Registration Form Changes

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/GDGSGOM#21]
**Note: All changes to be done on  gdgs24uat on RWB infra**
New Infra login: https://app.rwb.avniproject.org/#/home

- [x] In Farmer Registration, when a user selects "Marginal or Small" in the "Category of farmer", the question of upload Panchnama should be made compulsory. 
- [x] Upload Satbara is already compulsory (we need to cross check once if it is working), in Farmer Registration, when a user selects "Marginal or Small"
- [x] in Farmer Registration Form, mobile number does not have the rule of entering only 10 digits. It accepts alphabets as well. Entering Alphabet and more than 10 digits should not be allowed for
Witnes Contact 1
Witness Contact 2

- [x]  Daily Recording Farmer Form - If the farmer has carted silt for non-farm purpose, then the purpose of carting silt question should have 5 options (Kitchen Garden, Plot Leveling, Bunk Making, Road Construction, Others) Please remove agriculture as the option in this question

**Comment by Dinesh2019** [comment]
- [ ] Add more option is not displayed properly 

<img width="357" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWVEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--161064fedc14dda721bbe621b811d1f9b2737ab1/Screenshot%202024-02-23%20at%207.05.19%E2%80%AFAM.png" alt="Screenshot 2024-02-23 at 7.05.19 AM.png" />

**Comment by vedfordev** [comment]
@Dinesh2019 It is product bug. Raise issue in client and prioritise it.

**Comment by Dinesh2019** [comment]
Created the bug card in prod : https://github.com/avniproject/avni-client/issues/1318
