### ISSUE TITLE
[GDGS 2024] UAT: Work Order Endline

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/GDGSGOM#22]
*Note: All changes to be done on gdgs24uat on RWB infra
New Infra Link:
https://app.rwb.avniproject.org/#/home

- [x] In Work Order Endline form please remove the question "Please upload the post-work measurement image"

**Comment by vedfordev** [comment]
@AnjaliBhagabati done. moving to deploy ready.
