### ISSUE TITLE
{GDGS 2024] UAT: Farmer Endline Form

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/GDGSGOM#25]
Note: All changes to be done on UAT  RWB New Infra
https://app.rwb.avniproject.org/#/home

This is for both GDGS:& RWB:

- [ ]Farmer Endline Form:In the first question "The total farm area on which Silt is spread (acres)"  we need to add a rule, that the user cannot enter a figure which is more than the land holding of the farmer. The Land Holding of the farmer can be captured from the Farmer Registration form, question  "Land holding"

**Comment by sachsk** [comment]
@Dinesh2019 changes done on gsgs24uat, gdgsgom and rwb 24 uat

**Comment by sachsk** [comment]
@Dinesh2019 changes done on gsgs24uat, gdgsgom and rwb 24 uat

**Comment by sachsk** [comment]
@Dinesh2019 changes done on gsgs24uat, gdgsgom and rwb 24 uat
