### ISSUE TITLE
GDGS 2024: Offline dashboard cards

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/GDGSGOM#3]
## Context: 
As this will be the 3rd season of RWB implementations, the client is trying to reduce the issues that field staff is facing while accessing the app, below are the dashboard cards that will help users to find the pending task from the home dashboard only.

requirement sheet link: https://docs.google.com/spreadsheets/d/17-PuEEYXFgsCqm60Eg1QCj7LfIFVTbvZWx-I26ihBlM/edit#gid=1946734581

- [x]  count of work order for which daily recording is not done for today.
- [x]  Farmer endline not done
- [x]  Machine endline not done
- [x]  Work order endline not done
 
Note: changes are highlighted with green color as these are all new additions

**Comment by Dinesh2019** [comment]
Dashboard card is missing in the client app 

<img width="397" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEpEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aedebb0fd7c4725d27315f40af452d8d537c83c7/Screenshot%202023-12-08%20at%203.15.47%E2%80%AFPM.png" alt="Screenshot 2023-12-08 at 3.15.47 PM.png" />

**Comment by Dinesh2019** [comment]
- [x] count of active work orders we had the requirement change since it is not clear
