### ISSUE TITLE
GDGS 2024: Work order daily recording form changes

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/GDGSGOM#5]
# Context: 
the client has suggested the below changes related to daily encounters for the new season, based on issues field staff has faced in 2023, so we have agreed to make these changes on the new orgs that are created for the 2024 season.

- Daily recording farmer form changes document link: https://docs.google.com/spreadsheets/d/17-PuEEYXFgsCqm60Eg1QCj7LfIFVTbvZWx-I26ihBlM/edit#gid=1245159455
- [x] Work list updation rule has to be added as mentioned on the form requirement sheet
- [x] New question about silt used for other then farming purpose has to be added.
- [x] If the silt used for other than farming is responded yes then how much is used has also to be added.
- [x] changes in response options of question "What non-farm purpose was the silt used for?" & rule has to be removed that this question is shown in every form.

- Daily recording machine form changes document link: https://docs.google.com/spreadsheets/d/17-PuEEYXFgsCqm60Eg1QCj7LfIFVTbvZWx-I26ihBlM/edit#gid=1964309386
- [x] Work list updation rule has to be added as mentioned on the form requirement sheet

**Comment by adamsanadi6** [comment]
Created 2 new form elements in Daily recording farmer:
1. Purpose of carting silt
2. Other purpose of carting silt

**Comment by Dinesh2019** [comment]
- [x] Agriculture is not updated as Kitchen

**Comment by adamsanadi6** [comment]
@Dinesh2019  Removed the reamark and other purpose question from GDGS work order daily recording - former.
