### ISSUE TITLE
GDGS 2024: endline form changes

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/GDGSGOM#6]
## Context :
these changes are to be made on endline form for the 2024 season, changes are requested from client side to make it easier for user to do work on the app.

- Farmer endline form document link: https://docs.google.com/spreadsheets/d/17-PuEEYXFgsCqm60Eg1QCj7LfIFVTbvZWx-I26ihBlM/edit#gid=1675944884
- [x] Form level condition has to be added/ checked: this endline form should not be allowed to the user until at least 1 daily encounter has been captured on the respective farmer.
- [x] Total silt excavated question should auto populated number from the all the daily encounters captured against that particular farmer.
- [x] remove question related to dependent member count and voter Id marked with red color on the above sheet linked.

 - Machine endline form document link: https://docs.google.com/spreadsheets/d/17-PuEEYXFgsCqm60Eg1QCj7LfIFVTbvZWx-I26ihBlM/edit#gid=1988452945
- [x] Form level condition has to be added/ checked: this endline form should not be allowed to the user until at least 1 daily encounter has been captured on the respective machine.

 - Wor order endline form document link: https://docs.google.com/spreadsheets/d/17-PuEEYXFgsCqm60Eg1QCj7LfIFVTbvZWx-I26ihBlM/edit#gid=1063522284
- [x] form level condition has to be added/ modified: this form should not be allowed until all farmer endline, all machine endline and GP endline forms are submitted under this work order.

**Comment by BEULAHEVANJALIN** [comment]
"Gram Panchayat endline form" does not exist!

**Comment by Dinesh2019** [comment]
The work order endline is encountering it is not scheduled or not displaying the unplanned visit

**Comment by Dinesh2019** [comment]
@salilsamanvay @adamsanadi6 need a small clarification if all the endline is completed then only we have to schedule the work order endline if so we have to fix the issue
