### ISSUE TITLE
Live org creation

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/GDGSGOM#8]

**Comment by salilsamanvay** [comment]
will complete this card once UAT org is finalised

**Comment by sachsk** [comment]
link: https://app.rwb.avniproject.org

UAT org created on the new infra.

APP link:https://play.google.com/store/apps/details?id=com.openchsclient.gramin

**Comment by Dinesh2019** [comment]
- [x] Missing image for subject type for Excavating Machine and Work order 
- [x] Under search for search all we have to replace with All registration and enrolment text fields
- [x] Dashboard color is missing for the cards 
- [x] App format is not as per the Pervoius app Format
- [x] Back option is an error message displayed as Are you sure want to go back ? you will lose all the form changes but in the new version, we have diff message displayed need to fix this.
- [x] Setup fast sync is missing 
- [x] error message need to update to there is no specific value
- [x] Need to change the general encounter to new form 
- [x] Media sync is not happening
- [x] User group is need to be updated 




Webapp:

- [x] DAE showing some error 
<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3NNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c14287674dc896a448b83ffaaed761bb789d9e53/Screenshot%202024-01-30%20at%2011.18.48%E2%80%AFAM.png" alt="Screenshot 2024-01-30 at 11.18.48 AM.png" />

**Comment by Dinesh2019** [comment]
In Webapp the DAE is getting crash for subject type Farmer created the support ticket to fix this issue 
https://avni.freshdesk.com/a/tickets/3477
