### ISSUE TITLE
New Form for Lok-sahbhag

### ISSUE THREAD

**Issue by sachsk** [avniproject/GDGSGOM#9]
## Context
This is against old GDGS project not the 2024 implementation.

In the current GDGS project we take data against the workorder but in some places silt has been carted by the community without workorder so we client want to track those silt as well.
So we have decided to create new subject type lok sahabhag and in that registration nodal officer will fill the data against on the dam.

## Tech approach 
Do this on the GSGSGOM UAT (first check its updated or not)
After testing move to GDGSGOM

## Acceptance criteria
- [x] This will be a new subject type
- [x] All data will be capture in the registration
- [x] This will be saved on dam
- [x] Only nodal officer will able to fill this form

Fields are as follows:
Village Code (will be add later)
Name of WB
location(dam)
Total silt excavated
Start date
End date

additional request received from Hiral on 6th Dec 2023

- [x] Village code to be added after Village name as text
- [x] change in question language: Total silt excavated to be replaced with "Total silt excavated (in cu.m)
- [x] in Address allow user to select only till district level
- [x] add a question after Name of Waterbody: Name of Taluka and allow user to add text is response
- [x] change in question: Name of WB to be replaced with "Name of Waterbody"

**Comment by adamsanadi6** [comment]
Location type has been changed from Dam to District.

**Comment by Dinesh2019** [comment]
That looks good @adamsanadi6 you can move the changes to prod


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGs5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d70cd8970d826a53df525b886388e5c2e735dca2/Screen%20Recording%202023-12-07%20at%2012.22.26%E2%80%AFPM.mov

**Comment by Dinesh2019** [comment]
@sachsk @salilsamanvay do we need approval for this subject type as well

**Comment by sachsk** [comment]
No
